print(123456789)
print(3.14)
print("私は宇宙人だ")
print('お願いマッスル')

print(True)
print(False)
print("Hello" * 3)
print("Hello" * 2)
print("Hello world")
print(3 + 4)
# print(10 + "円拾った")
print(3, "Hello", 4)
print(3, 4, sep="")
print("Hello", "World", sep="-")
print("hello", 100, "人の友達", sep="\n")
print("Hello world", end="\n")
print("HEllo world", end="!!!")